#!/bin/bash
# Install AWS CodeStar remote access management.
# Allows project members to remotely access Amazon EC2 instances running Linux associated with the project.
wget -O /usr/local/bin/get_authorized_keys https://s3.amazonaws.com/awscodestar-remote-access-us-east-1/get_authorized_keys
chmod 755 /usr/local/bin/get_authorized_keys
echo 'AuthorizedKeysCommand /usr/local/bin/get_authorized_keys' >> /etc/ssh/sshd_config
echo 'AuthorizedKeysCommandUser root' >> /etc/ssh/sshd_config
service sshd restart
apt-get install python-pip -y
pip install --upgrade --user awscli
# Install pip and python dev libraries.
pip install boto3
pip install boto
pip install pycrypto
